---
- name:  Create /xroad directory
  become: yes
  file: path=/xroad state=directory mode=0755

- import_tasks: ubuntu.yml
  when: ansible_os_family == "Debian"

- import_tasks: rhel.yml
  when: ansible_os_family == "RedHat"
